"""Generate the Agent Graph Mermaid diagram from the registry + compiled graph.

Outputs:
    docs/agent_graph.md   — Mermaid fenced block + registered-agents markdown table
    docs/agent_graph.svg  — Mermaid PNG/SVG render (best-effort, requires mermaid CLI)

Run from the project root:
    python scripts/generate_agent_graph.py

The output is meant to be referenced from README.md. After changing the agent
registry or graph wiring, re-run this script and commit the regenerated files.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

# Make `app` importable when running this script from the project root.
ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

os.environ.setdefault("APP_ENV", "development")

from app.agents.graph import build_orchestrator_graph  # noqa: E402
from app.agents.registry import AGENT_REGISTRY, TERMINAL_NODES  # noqa: E402


def build_mermaid(graph) -> str:
    """Try the LangGraph helper first; fall back to a hand-rolled diagram."""
    try:
        return graph.get_graph().draw_mermaid()
    except Exception:
        lines = ["graph TD", "  START([START]) --> route_intent"]
        for key in AGENT_REGISTRY:
            lines.append(f"  route_intent -. intent: {key} .-> {key}")
            lines.append(f"  {key} --> response_agent")
        for term in TERMINAL_NODES:
            if term == "response_agent":
                lines.append("  response_agent --> END([END])")
            else:
                lines.append(f"  route_intent -. intent: {term} .-> {term}")
                lines.append(f"  {term} --> END([END])")
        return "\n".join(lines)


def build_agents_table() -> str:
    """Build a markdown table summarising the registered agents."""
    headers = ["Key", "Name", "Capabilities", "Intents", "Tools"]
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    for spec in AGENT_REGISTRY.values():
        row = [
            f"`{spec.key}`",
            spec.name,
            ", ".join(spec.capabilities),
            ", ".join(spec.intents),
            ", ".join(f"`{t}`" for t in spec.tools),
        ]
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def build_routing_example() -> str:
    """Build a small text example showing how a query flows through the graph."""
    return (
        "User: \"Mua 50 thùng giấy A4 thì giá sỉ bao nhiêu?\"\n"
        "\n"
        "  → route_intent           (intent: `wholesale_pricing`, "
        "entities: {product: A4, quantity: 50})\n"
        "  → product_agent          (queries products + inventory + price_tiers)\n"
        "  → response_agent         (composes final answer with sources)\n"
    )


def main() -> int:
    out_dir = ROOT / "docs"
    out_dir.mkdir(parents=True, exist_ok=True)
    md_path = out_dir / "agent_graph.md"

    # Build the graph with a memory checkpointer (no DB needed for diagram generation).
    graph = build_orchestrator_graph()
    diagram = build_mermaid(graph)
    table = build_agents_table()
    example = build_routing_example()

    md = (
        "# Agent Architecture (auto-generated)\n"
        "\n"
        "This file is generated by `scripts/generate_agent_graph.py`. "
        "Do not edit by hand — re-run the script after changing the registry.\n"
        "\n"
        "## LangGraph Orchestrator\n"
        "\n"
        "```mermaid\n"
        f"{diagram}\n"
        "```\n"
        "\n"
        "## Registered Agents\n"
        "\n"
        f"{table}\n"
        "\n"
        "## Routing example\n"
        "\n"
        "```text\n"
        f"{example}\n"
        "```\n"
    )

    md_path.write_text(md, encoding="utf-8")
    print(f"wrote {md_path} ({len(md)} bytes)")

    # Best-effort SVG render. Requires `mmdc` (Mermaid CLI) on PATH.
    try:
        import subprocess

        svg_path = out_dir / "agent_graph.svg"
        # Extract the mermaid block to a temp file, then run mmdc.
        tmp = out_dir / "_agent_graph.mmd"
        tmp.write_text(diagram, encoding="utf-8")
        subprocess.run(
            ["mmdc", "-i", str(tmp), "-o", str(svg_path), "-q"],
            check=True,
            timeout=30,
        )
        tmp.unlink(missing_ok=True)
        print(f"wrote {svg_path}")
    except FileNotFoundError:
        print("mmdc not found, skipping SVG render (install mermaid-cli to enable)")
    except Exception as e:
        print(f"SVG render failed: {e}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
