---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	route_intent(route_intent)
	product_agent(product_agent)
	order_agent(order_agent)
	policy_rag_agent(policy_rag_agent)
	sales_recommendation_agent(sales_recommendation_agent)
	refund_decision_agent(refund_decision_agent)
	response_agent(response_agent)
	human_escalation(human_escalation)
	__end__([<p>__end__</p>]):::last
	__start__ --> route_intent;
	order_agent --> response_agent;
	policy_rag_agent --> response_agent;
	product_agent --> response_agent;
	refund_decision_agent --> response_agent;
	route_intent -.-> human_escalation;
	route_intent -.-> order_agent;
	route_intent -.-> policy_rag_agent;
	route_intent -.-> product_agent;
	route_intent -.-> refund_decision_agent;
	route_intent -.-> response_agent;
	route_intent -.-> sales_recommendation_agent;
	sales_recommendation_agent --> response_agent;
	human_escalation --> __end__;
	response_agent --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
